name: Publish Python Package to PyPI

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: pypi # Optional, if using a dedicated environment for publishing

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build distribution
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v2
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }} # Referencing the secret
